language: php

php:
 - 7.0

before_script:
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0

script:
 - ./tests/travis.sh

notifications:
 email: false
 webhooks: http://melban.com/webhook/discord.php
